In [1]:
import csv
import pandas as pd
import seaborn as sns

In [2]:
node_info = pd.read_csv("data/node_information.csv", names = ["Id","Pubyear","Title","Authors","Journal","Abstract"])
node_edges = pd.read_csv("data/training_set.csv", delimiter=" ", names = ["Source","Target","Type"])

In [4]:
ev = node_edges[node_edges["Type"]==1].values

In [5]:
l1 = node_info[node_info["Id"]==ev[4][0]]

In [6]:
l1["Pubyear"].values[0]

1997

In [11]:
p = []
m = []
a = 0
for i in ev:
    a+=1
    year1 = node_info[node_info["Id"]==i[0]]["Pubyear"].values[0]
    year2 = node_info[node_info["Id"]==i[1]]["Pubyear"].values[0]
    delta = year1-year2
    if delta > 0:
        p.append(delta)
    if delta < 0:
        m.append(delta)
    if a > 10000:
        break

In [6]:
node_info = node_info[["Id","Pubyear"]]

In [7]:
a = pd.merge(left = node_edges,right=node_info,left_on="Source",right_on="Id")

In [9]:
a = pd.merge(left = a,right=node_info,left_on="Target",right_on="Id")

         Source   Target  Type     Id_x  Pubyear_x     Id_y  Pubyear_y
0       9510123  9502114     1  9510123       1995  9502114       1995
1       9604093  9502114     1  9604093       1996  9502114       1995
2       9601150  9502114     0  9601150       1996  9502114       1995
3       9703014  9502114     0  9703014       1997  9502114       1995
4       9603017  9502114     1  9603017       1996  9502114       1995
5       9509112  9502114     1  9509112       1995  9502114       1995
6       9607084  9502114     0  9607084       1996  9502114       1995
7       9404020  9502114     0  9404020       1994  9502114       1995
8       9507085  9502114     0  9507085       1995  9502114       1995
9       9609145  9502114     0  9609145       1996  9502114       1995
10      9912022  9502114     0  9912022       1999  9502114       1995
11      9404081  9502114     0  9404081       1994  9502114       1995
12       303005  9502114     0   303005       2003  9502114       1995
13         1089  9502114     0     1089       2000  9502114       1995
14       102066  9502114     0   102066       2001  9502114       1995
15      9603043  9502114     1  9603043       1996  9502114       1995
16      9911015  9502114     0  9911015       1999  9502114       1995
17      9603170  9502114     1  9603170       1996  9502114       1995
18      9810055  9502114     1  9810055       1998  9502114       1995
19      9510122  9502114     1  9510122       1995  9502114       1995
20      9510123  9408144     1  9510123       1995  9408144       1994
21      9907198  9408144     0  9907198       1999  9408144       1994
22         1067  9408144     0     1067       2000  9408144       1994
23      9910028  9408144     0  9910028       1999  9408144       1994
24       109083  9408144     0   109083       2003  9408144       1994
25      9610031  9408144     0  9610031       1996  9408144       1994
26       207072  9408144     0   207072       2002  9408144       1994
27      9509141  9408144     0  9509141       1995  9408144       1994
28         8016  9408144     0     8016       2000  9408144       1994
29       101019  9408144     0   101019       2001  9408144       1994
...         ...      ...   ...      ...        ...      ...        ...
615482    12159   304266     0    12159       2000   304266       2003
615483  9403038   304266     0  9403038       1994   304266       2003
615484  9312006   304266     0  9312006       1993   304266       2003
615485  9308126   304266     0  9308126       1993   304266       2003
615486   105249   304266     0   105249       2001   304266       2003
615487  9411017  9312092     0  9411017       1994  9312092       1993
615488  9702021  9312092     0  9702021       1997  9312092       1993
615489  9503215  9312092     0  9503215       1995  9312092       1993
615490  9405065  9312092     0  9405065       1994  9312092       1993
615491  9404100  9312092     1  9404100       1994  9312092       1993
615492  9406201  9312092     0  9406201       1994  9312092       1993
615493  9806171    11232     0  9806171       1998    11232       2001
615494     5024    11232     0     5024       2000    11232       2001
615495  9611098    11232     0  9611098       1996    11232       2001
615496  9311089    11232     0  9311089       1994    11232       2001
615497  9307182    12066     0  9307182       1993    12066       2000
615498  9808063    12066     0  9808063       1998    12066       2000
615499  9310098    12066     0  9310098       1993    12066       2000
615500     9092    12066     0     9092       2000    12066       2000
615501  9603039    12066     0  9603039       1996    12066       2000
615502  9605067   102191     0  9605067       1996   102191       2002
615503   205018   102191     1   205018       2002   102191       2002
615504   302130   102191     1   302130       2003   102191       2002
615505     3097   102191     0     3097       2000   102191       2002
615506  9911133   102191     0  9911133       1999   102191       2002
615507  9910133   106045     0  9910133       1999   106045       2001
615508  9901003   106045     0  9901003       1999   106045       2001
615509   202019   106045     0   202019       2002   106045       2001
615510  9506175   106045     0  9506175       1995   106045       2001
615511   106170   106045     0   106170       2001   106045       2001

[615512 rows x 7 columns]